/**
 * NoesisRushHour 의 XAML 을 만든다.
 *
 *   node Documents/Tools/build_noesis_rushhour_xaml.js
 *
 * 조각 자리(P1..Pn)와 도착 포인트 자리(E1..En)는 같은 덩어리의 반복이라 손으로 쓰지 않고 여기서 찍는다.
 * 자리 수를 바꾸면 `NoesisRushHour_Panel.ts` 의 PIECE_SLOTS / END_POINT_SLOTS 도 같이 바꾼다.
 * 행 비율은 `PuzzleUI_RelativeLayout.ts` 의 상수와 같아야 한다 (위 6 · 아래 8 · 보드 7 : 보조 3).
 */
const fs = require('fs');
const path = require('path');

const PIECE_SLOTS = 12;
const END_POINT_SLOTS = 2;
const GRID = 7;

const TOP_INSET = 6;
const BOTTOM_INSET = 8;
const BOARD_FLEX = 7;
const AUX_FLEX = 3;
const usable = 100 - TOP_INSET - BOTTOM_INSET;
const boardRow = (usable * BOARD_FLEX / (BOARD_FLEX + AUX_FLEX)).toFixed(1);
const auxRow = (usable * AUX_FLEX / (BOARD_FLEX + AUX_FLEX)).toFixed(1);

const OUTPUT = path.join(__dirname, '..', 'NoesisSample', 'NoesisRushHour', 'RushHourBoard.xaml');

function sizeReport(indent) {
	return [
		`${indent}<b:InvokeCommandAction Command="{Binding OnRootWidth}" CommandParameter="{Binding ActualWidth, ElementName=Root}"/>`,
		`${indent}<b:InvokeCommandAction Command="{Binding OnRootHeight}" CommandParameter="{Binding ActualHeight, ElementName=Root}"/>`,
	].join('\n');
}

function cells() {
	const lines = [];
	for (let i = 0; i < GRID * GRID; i++) {
		lines.push('\t\t\t\t<Border Style="{StaticResource CellBox}"/>');
	}
	return lines.join('\n');
}

function endPoint(n) {
	const p = `E${n}`;
	return `
		<Grid Canvas.Left="{Binding ${p}X}" Canvas.Top="{Binding ${p}Y}" Width="{Binding ${p}Size}" Height="{Binding ${p}Size}" IsHitTestVisible="False">
			<Border Style="{StaticResource PortBase}"/>
			<Border Style="{StaticResource PortRed}" Opacity="{Binding ${p}Red}"/>
			<Border Style="{StaticResource PortBlue}" Opacity="{Binding ${p}Blue}"/>
		</Grid>`;
}

function piece(n) {
	const p = `P${n}`;
	return `
		<Canvas Canvas.Left="{Binding ${p}TL}" Canvas.Top="{Binding ${p}TT}" Width="{Binding ${p}TW}" Height="{Binding ${p}TH}">
			<Grid Width="{Binding ${p}W}" Height="{Binding ${p}H}" Background="Transparent">
				<b:Interaction.Behaviors>
					<b:MouseDragElementBehavior ConstrainToParentBounds="True" X="{Binding ${p}X, Mode=TwoWay}" Y="{Binding ${p}Y, Mode=TwoWay}"/>
				</b:Interaction.Behaviors>
				<b:Interaction.Triggers>
					<b:EventTrigger EventName="MouseLeftButtonUp">
						<b:InvokeCommandAction Command="{Binding On${p}Up}"/>
					</b:EventTrigger>
					<b:EventTrigger EventName="TouchUp">
						<b:InvokeCommandAction Command="{Binding On${p}Up}"/>
					</b:EventTrigger>
					<b:EventTrigger EventName="LostMouseCapture">
						<b:InvokeCommandAction Command="{Binding On${p}Up}"/>
					</b:EventTrigger>
				</b:Interaction.Triggers>
				<Border Style="{StaticResource FaceBlock}"/>
				<Border Style="{StaticResource FaceRed}" Opacity="{Binding ${p}Red}"/>
				<Border Style="{StaticResource FaceBlue}" Opacity="{Binding ${p}Blue}"/>
				<TextBlock Style="{StaticResource PieceLabel}" Text="{Binding ${p}Label}" FontSize="{Binding FontMedium}"/>
			</Grid>
		</Canvas>`;
}

function repeat(count, make) {
	const parts = [];
	for (let n = 1; n <= count; n++) {
		parts.push(make(n));
	}
	return parts.join('');
}

const xaml = `<!--
  NoesisRushHour - the puzzle board screen, drawn by Noesis.  GENERATED: edit
  Documents/Tools/build_noesis_rushhour_xaml.js and run it again, do not edit this file.

  Rows follow PuzzleBoardUI_Panel: top inset ${TOP_INSET}% / board ${BOARD_FLEX} : aux ${AUX_FLEX} / bottom inset ${BOTTOM_INSET}%.
  The bars are laid out here. The board, the end points and the pieces are positioned by the
  script (NoesisRushHour_Panel.ts) in root pixels, because MouseDragElementBehavior reports X / Y
  in root pixels. The script learns the root size from OnRootWidth / OnRootHeight below.
-->
<Grid
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:b="http://schemas.microsoft.com/xaml/behaviors"
	x:Name="Root" Background="#FF14171F">

	<Grid.Resources>
		<Style x:Key="BarButton" TargetType="Button">
			<Setter Property="Foreground" Value="#FFFFFFFF"/>
			<Setter Property="FontWeight" Value="Bold"/>
			<Setter Property="Template">
				<Setter.Value>
					<ControlTemplate TargetType="Button">
						<Border x:Name="Bd" Background="{TemplateBinding Background}" CornerRadius="10">
							<ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/>
						</Border>
						<ControlTemplate.Triggers>
							<Trigger Property="IsPressed" Value="True">
								<Setter TargetName="Bd" Property="Opacity" Value="0.7"/>
							</Trigger>
						</ControlTemplate.Triggers>
					</ControlTemplate>
				</Setter.Value>
			</Setter>
		</Style>

		<Style x:Key="CellBox" TargetType="Border">
			<Setter Property="Margin" Value="1.5"/>
			<Setter Property="CornerRadius" Value="6"/>
			<Setter Property="Background" Value="#FF1F212E"/>
		</Style>

		<Style x:Key="PortBase" TargetType="Border">
			<Setter Property="Margin" Value="1.5"/>
			<Setter Property="CornerRadius" Value="6"/>
			<Setter Property="Background" Value="#FF0B0D12"/>
		</Style>
		<Style x:Key="PortRed" TargetType="Border" BasedOn="{StaticResource PortBase}">
			<Setter Property="Background" Value="#40E11D48"/>
			<Setter Property="BorderBrush" Value="#FFE11D48"/>
			<Setter Property="BorderThickness" Value="4"/>
		</Style>
		<Style x:Key="PortBlue" TargetType="Border" BasedOn="{StaticResource PortBase}">
			<Setter Property="Background" Value="#403B82F6"/>
			<Setter Property="BorderBrush" Value="#FF3B82F6"/>
			<Setter Property="BorderThickness" Value="4"/>
		</Style>

		<Style x:Key="FaceBlock" TargetType="Border">
			<Setter Property="CornerRadius" Value="10"/>
			<Setter Property="Background" Value="#FF64748B"/>
			<Setter Property="BorderBrush" Value="#FF94A3B8"/>
			<Setter Property="BorderThickness" Value="3"/>
			<Setter Property="IsHitTestVisible" Value="False"/>
		</Style>
		<Style x:Key="FaceRed" TargetType="Border" BasedOn="{StaticResource FaceBlock}">
			<Setter Property="Background" Value="#FFE11D48"/>
			<Setter Property="BorderBrush" Value="#FFFDA4AF"/>
		</Style>
		<Style x:Key="FaceBlue" TargetType="Border" BasedOn="{StaticResource FaceBlock}">
			<Setter Property="Background" Value="#FF3B82F6"/>
			<Setter Property="BorderBrush" Value="#FF93C5FD"/>
		</Style>
		<Style x:Key="PieceLabel" TargetType="TextBlock">
			<Setter Property="Foreground" Value="#FFFFFFFF"/>
			<Setter Property="FontWeight" Value="Bold"/>
			<Setter Property="HorizontalAlignment" Value="Center"/>
			<Setter Property="VerticalAlignment" Value="Center"/>
			<Setter Property="IsHitTestVisible" Value="False"/>
		</Style>
	</Grid.Resources>

	<!-- Root size report. The press trigger doubles as "tap to start", so the size is known before play. -->
	<b:Interaction.Triggers>
		<b:EventTrigger EventName="Loaded">
${sizeReport('\t\t\t')}
		</b:EventTrigger>
		<b:EventTrigger EventName="SizeChanged">
${sizeReport('\t\t\t')}
		</b:EventTrigger>
		<b:EventTrigger EventName="PreviewMouseLeftButtonDown">
${sizeReport('\t\t\t')}
			<b:InvokeCommandAction Command="{Binding OnRootTap}"/>
		</b:EventTrigger>
	</b:Interaction.Triggers>

	<Grid.RowDefinitions>
		<RowDefinition Height="${TOP_INSET}*"/>
		<RowDefinition Height="${boardRow}*"/>
		<RowDefinition Height="${auxRow}*"/>
		<RowDefinition Height="${BOTTOM_INSET}*"/>
	</Grid.RowDefinitions>

	<!-- Top inset: title and move count. -->
	<Grid Grid.Row="0">
		<Grid.ColumnDefinitions>
			<ColumnDefinition Width="3*"/>
			<ColumnDefinition Width="94*"/>
			<ColumnDefinition Width="3*"/>
		</Grid.ColumnDefinitions>
		<TextBlock Grid.Column="1" Text="{Binding TitleText}" FontSize="{Binding FontLarge}" FontWeight="Bold"
				   Foreground="#FFFFFFFF" HorizontalAlignment="Left" VerticalAlignment="Bottom"/>
		<TextBlock Grid.Column="1" Text="{Binding MovesText}" FontSize="{Binding FontLarge}" FontWeight="Bold"
				   Foreground="#FFF2CC40" HorizontalAlignment="Right" VerticalAlignment="Bottom"/>
	</Grid>

	<!-- Aux area: hint and Reset. -->
	<Grid Grid.Row="2">
		<Grid.ColumnDefinitions>
			<ColumnDefinition Width="3*"/>
			<ColumnDefinition Width="94*"/>
			<ColumnDefinition Width="3*"/>
		</Grid.ColumnDefinitions>
		<Grid.RowDefinitions>
			<RowDefinition Height="8*"/>
			<RowDefinition Height="84*"/>
			<RowDefinition Height="8*"/>
		</Grid.RowDefinitions>
		<Border Grid.Row="1" Grid.Column="1" Background="#FF1C1F2B" CornerRadius="14">
			<Grid>
				<Grid.ColumnDefinitions>
					<ColumnDefinition Width="4*"/>
					<ColumnDefinition Width="70*"/>
					<ColumnDefinition Width="2*"/>
					<ColumnDefinition Width="20*"/>
					<ColumnDefinition Width="4*"/>
				</Grid.ColumnDefinitions>
				<Grid.RowDefinitions>
					<RowDefinition Height="15*"/>
					<RowDefinition Height="70*"/>
					<RowDefinition Height="15*"/>
				</Grid.RowDefinitions>
				<TextBlock Grid.Row="1" Grid.Column="1" Text="{Binding HintText}" FontSize="{Binding FontMedium}"
						   Foreground="#FFCBD5E1" TextWrapping="Wrap" VerticalAlignment="Center"/>
				<Button Grid.Row="1" Grid.Column="3" Style="{StaticResource BarButton}" Background="#FF52576B"
						Content="Reset" FontSize="{Binding FontMedium}" Command="{Binding OnReset}"/>
			</Grid>
		</Border>
	</Grid>

	<!-- Bottom inset: diagnostics (test build only) and Menu. -->
	<Grid Grid.Row="3">
		<Grid.ColumnDefinitions>
			<ColumnDefinition Width="3*"/>
			<ColumnDefinition Width="72*"/>
			<ColumnDefinition Width="22*"/>
			<ColumnDefinition Width="3*"/>
		</Grid.ColumnDefinitions>
		<Grid.RowDefinitions>
			<RowDefinition Height="14*"/>
			<RowDefinition Height="72*"/>
			<RowDefinition Height="14*"/>
		</Grid.RowDefinitions>
		<TextBlock Grid.Row="1" Grid.Column="1" Text="{Binding DiagText}" FontSize="{Binding FontSmall}"
				   Foreground="#FF64748B" TextWrapping="Wrap" VerticalAlignment="Center"/>
		<Button Grid.Row="1" Grid.Column="2" Style="{StaticResource BarButton}" Background="#FF3D455C" Opacity="0.92"
				Content="Menu" FontSize="{Binding FontMedium}" Command="{Binding OnMenu}"/>
	</Grid>

	<!-- Board layer: everything here is placed by the script in root pixels. -->
	<Canvas Grid.RowSpan="4">
		<Border Canvas.Left="{Binding BoardX}" Canvas.Top="{Binding BoardY}" Width="{Binding BoardSize}" Height="{Binding BoardSize}"
				Background="#FF0E1017" CornerRadius="10" IsHitTestVisible="False">
			<UniformGrid Rows="${GRID}" Columns="${GRID}">
${cells()}
			</UniformGrid>
		</Border>
${repeat(END_POINT_SLOTS, endPoint)}
${repeat(PIECE_SLOTS, piece)}

		<!-- Input lock + banner. LockSize is 0 while playing, the board size otherwise. -->
		<Border Canvas.Left="{Binding BoardX}" Canvas.Top="{Binding BoardY}" Width="{Binding LockSize}" Height="{Binding LockSize}"
				Background="#B30A0C12" CornerRadius="10">
			<TextBlock Text="{Binding BannerText}" FontSize="{Binding FontLarge}" FontWeight="Bold" Foreground="#FFF2CC40"
					   HorizontalAlignment="Center" VerticalAlignment="Center" IsHitTestVisible="False"/>
		</Border>
	</Canvas>
</Grid>
`;

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, xaml, 'utf8');
console.log(`wrote ${OUTPUT} (${PIECE_SLOTS} piece slots, ${END_POINT_SLOTS} end point slots)`);
