/**
 * NoesisMoveLab 의 XAML 을 만든다.
 *
 *   node Documents/Tools/build_noesis_movelab_xaml.js
 *
 * `build_noesis_rushhour_xaml.js` 와 같은 화면이다. 다른 점은 둘이다 -
 *   - 조각에 드래그 Behavior 가 없다. 입력을 받지 않는 그림이고 `TranslateTransform` 으로만 움직인다
 *   - 루트가 Down / Move / Up 을 `PassEventArgsToCommand="True"` 로 스크립트에 넘긴다 (공식 문서의 MouseMove 예제)
 * 자리 수를 바꾸면 `NoesisMoveLab_Panel.ts` 의 PIECE_SLOTS / END_POINT_SLOTS 도 같이 바꾼다.
 */
const fs = require('fs');
const path = require('path');

const PIECE_SLOTS = 12;
const END_POINT_SLOTS = 2;
const GRID = 7;

const TOP_INSET = 6;
const BOTTOM_INSET = 8;
const BOARD_FLEX = 7;
const AUX_FLEX = 3;
const usable = 100 - TOP_INSET - BOTTOM_INSET;
const boardRow = (usable * BOARD_FLEX / (BOARD_FLEX + AUX_FLEX)).toFixed(1);
const auxRow = (usable * AUX_FLEX / (BOARD_FLEX + AUX_FLEX)).toFixed(1);

const OUTPUT_DIR = path.join(__dirname, '..', 'NoesisSample', 'NoesisMoveLab');

function sizeReport(indent) {
	return [
		`${indent}<b:InvokeCommandAction Command="{Binding OnRootWidth}" CommandParameter="{Binding ActualWidth, ElementName=Root}"/>`,
		`${indent}<b:InvokeCommandAction Command="{Binding OnRootHeight}" CommandParameter="{Binding ActualHeight, ElementName=Root}"/>`,
	].join('\n');
}

/**
 * 포인터 이벤트를 인자째 넘기는 트리거.
 *
 * `pointers: false` 면 아예 내보내지 않는다 - 화면이 안 뜨는 원인이 `PassEventArgsToCommand` 인지
 * 가르기 위한 것이다 (`MoveLabMini.xaml`).
 */
function pointerTriggers(options) {
	if (options.pointers === false) {
		return '\t\t<!-- Pointer triggers left out on purpose: this page only proves the rest loads. -->';
	}
	const pairs = [
		['MouseLeftButtonDown', 'OnMouseDown'], ['MouseMove', 'OnMouseMove'], ['MouseLeftButtonUp', 'OnMouseUp'],
		['TouchDown', 'OnTouchDown'], ['TouchMove', 'OnTouchMove'], ['TouchUp', 'OnTouchUp'],
	];
	return pairs.map(([eventName, command]) => [
		`\t\t<b:EventTrigger EventName="${eventName}">`,
		`\t\t\t<b:InvokeCommandAction Command="{Binding ${command}}" PassEventArgsToCommand="True"/>`,
		'\t\t</b:EventTrigger>',
	].join('\n')).join('\n');
}

function cells() {
	const lines = [];
	for (let i = 0; i < GRID * GRID; i++) {
		lines.push('\t\t\t\t<Border Style="{StaticResource CellBox}"/>');
	}
	return lines.join('\n');
}

function endPoint(n) {
	const p = `E${n}`;
	return `
		<Grid Canvas.Left="{Binding ${p}X}" Canvas.Top="{Binding ${p}Y}" Width="{Binding ${p}Size}" Height="{Binding ${p}Size}">
			<Border Style="{StaticResource PortBase}"/>
			<Border Style="{StaticResource PortRed}" Opacity="{Binding ${p}Red}"/>
			<Border Style="{StaticResource PortBlue}" Opacity="{Binding ${p}Blue}"/>
		</Grid>`;
}

/**
 * 조각 하나. 자리를 잡는 방법이 둘이다 -
 *   transform: `TranslateTransform` 에 X/Y 를 묶는다 (공식 MouseMove 예제의 방식)
 *   canvas   : `Canvas.Left/Top` 에 묶는다 (러시아워 샘플에서 이미 그려진 것이 확인된 방식)
 * 둘은 같은 dataContext 를 쓰므로 스크립트는 그대로다.
 */
function piece(n, mode) {
	const p = `P${n}`;
	const open = mode === 'canvas'
		? `\t\t<Grid Canvas.Left="{Binding ${p}X}" Canvas.Top="{Binding ${p}Y}" Width="{Binding ${p}W}" Height="{Binding ${p}H}">`
		: [
			`\t\t<Grid Width="{Binding ${p}W}" Height="{Binding ${p}H}">`,
			'\t\t\t<Grid.RenderTransform>',
			`\t\t\t\t<TranslateTransform X="{Binding ${p}X}" Y="{Binding ${p}Y}"/>`,
			'\t\t\t</Grid.RenderTransform>',
		].join('\n');
	return `
${open}
			<Border Style="{StaticResource FaceBlock}"/>
			<Border Style="{StaticResource FaceRed}" Opacity="{Binding ${p}Red}"/>
			<Border Style="{StaticResource FaceBlue}" Opacity="{Binding ${p}Blue}"/>
			<Border Style="{StaticResource FaceHot}" Opacity="{Binding ${p}Hot}"/>
			<TextBlock Style="{StaticResource PieceLabel}" Text="{Binding ${p}Label}" FontSize="{Binding FontMedium}"/>
		</Grid>`;
}

function repeat(count, make) {
	const parts = [];
	for (let n = 1; n <= count; n++) {
		parts.push(make(n));
	}
	return parts.join('');
}

function render(options) {
	return `<!--
  NoesisMoveLab (${options.note}) - Rush Hour dragged BY THE SCRIPT from pointer coordinates.
  GENERATED: edit Documents/Tools/build_noesis_movelab_xaml.js and run it again, do not edit this file.

  The root passes Down / Move / Up to the script with PassEventArgsToCommand="True" (args.position).
  Nothing on the board takes input: the script decides which piece was grabbed from the coordinates
  and moves it by writing the piece's position. Script: NoesisMoveLab_Panel.ts (the same one for
  all three pages, so only the gizmo's Root XAML changes).
-->
<Grid
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:b="http://schemas.microsoft.com/xaml/behaviors"
	x:Name="Root" Background="#FF14171F">

	<Grid.Resources>
		<Style x:Key="BarButton" TargetType="Button">
			<Setter Property="Foreground" Value="#FFFFFFFF"/>
			<Setter Property="FontWeight" Value="Bold"/>
			<Setter Property="Template">
				<Setter.Value>
					<ControlTemplate TargetType="Button">
						<Border x:Name="Bd" Background="{TemplateBinding Background}" CornerRadius="10">
							<ContentPresenter HorizontalAlignment="Center" VerticalAlignment="Center"/>
						</Border>
						<ControlTemplate.Triggers>
							<Trigger Property="IsPressed" Value="True">
								<Setter TargetName="Bd" Property="Opacity" Value="0.7"/>
							</Trigger>
						</ControlTemplate.Triggers>
					</ControlTemplate>
				</Setter.Value>
			</Setter>
		</Style>

		<Style x:Key="CellBox" TargetType="Border">
			<Setter Property="Margin" Value="1.5"/>
			<Setter Property="CornerRadius" Value="6"/>
			<Setter Property="Background" Value="#FF1F212E"/>
		</Style>

		<Style x:Key="PortBase" TargetType="Border">
			<Setter Property="Margin" Value="1.5"/>
			<Setter Property="CornerRadius" Value="6"/>
			<Setter Property="Background" Value="#FF0B0D12"/>
		</Style>
		<Style x:Key="PortRed" TargetType="Border" BasedOn="{StaticResource PortBase}">
			<Setter Property="Background" Value="#40E11D48"/>
			<Setter Property="BorderBrush" Value="#FFE11D48"/>
			<Setter Property="BorderThickness" Value="4"/>
		</Style>
		<Style x:Key="PortBlue" TargetType="Border" BasedOn="{StaticResource PortBase}">
			<Setter Property="Background" Value="#403B82F6"/>
			<Setter Property="BorderBrush" Value="#FF3B82F6"/>
			<Setter Property="BorderThickness" Value="4"/>
		</Style>

		<Style x:Key="FaceBlock" TargetType="Border">
			<Setter Property="CornerRadius" Value="10"/>
			<Setter Property="Background" Value="#FF64748B"/>
			<Setter Property="BorderBrush" Value="#FF94A3B8"/>
			<Setter Property="BorderThickness" Value="3"/>
		</Style>
		<Style x:Key="FaceRed" TargetType="Border" BasedOn="{StaticResource FaceBlock}">
			<Setter Property="Background" Value="#FFE11D48"/>
			<Setter Property="BorderBrush" Value="#FFFDA4AF"/>
		</Style>
		<Style x:Key="FaceBlue" TargetType="Border" BasedOn="{StaticResource FaceBlock}">
			<Setter Property="Background" Value="#FF3B82F6"/>
			<Setter Property="BorderBrush" Value="#FF93C5FD"/>
		</Style>
		<!-- The grabbed piece: a bright rim on top of whatever face it has. -->
		<Style x:Key="FaceHot" TargetType="Border">
			<Setter Property="CornerRadius" Value="10"/>
			<Setter Property="BorderBrush" Value="#FFFFF299"/>
			<Setter Property="BorderThickness" Value="5"/>
		</Style>
		<Style x:Key="PieceLabel" TargetType="TextBlock">
			<Setter Property="Foreground" Value="#FFFFFFFF"/>
			<Setter Property="FontWeight" Value="Bold"/>
			<Setter Property="HorizontalAlignment" Value="Center"/>
			<Setter Property="VerticalAlignment" Value="Center"/>
		</Style>
	</Grid.Resources>

	<!--
	  Pointer events with their arguments. Mouse and Touch go to separate commands so the script can
	  show which ones arrive on a phone and what their arguments look like; whichever source grabs a
	  piece first drives that drag.
	-->
	<b:Interaction.Triggers>
${pointerTriggers(options)}
		<b:EventTrigger EventName="Loaded">
${sizeReport('\t\t\t')}
		</b:EventTrigger>
		<b:EventTrigger EventName="SizeChanged">
${sizeReport('\t\t\t')}
		</b:EventTrigger>
		<b:EventTrigger EventName="PreviewMouseLeftButtonDown">
${sizeReport('\t\t\t')}
		</b:EventTrigger>
	</b:Interaction.Triggers>

	<Grid.RowDefinitions>
		<RowDefinition Height="${TOP_INSET}*"/>
		<RowDefinition Height="${boardRow}*"/>
		<RowDefinition Height="${auxRow}*"/>
		<RowDefinition Height="${BOTTOM_INSET}*"/>
	</Grid.RowDefinitions>

	<!-- Top inset: title and move count. -->
	<Grid Grid.Row="0" IsHitTestVisible="False">
		<Grid.ColumnDefinitions>
			<ColumnDefinition Width="3*"/>
			<ColumnDefinition Width="94*"/>
			<ColumnDefinition Width="3*"/>
		</Grid.ColumnDefinitions>
		<TextBlock Grid.Column="1" Text="{Binding TitleText}" FontSize="{Binding FontLarge}" FontWeight="Bold"
				   Foreground="#FFFFFFFF" HorizontalAlignment="Left" VerticalAlignment="Bottom"/>
		<TextBlock Grid.Column="1" Text="{Binding MovesText}" FontSize="{Binding FontLarge}" FontWeight="Bold"
				   Foreground="#FFF2CC40" HorizontalAlignment="Right" VerticalAlignment="Bottom"/>
	</Grid>

	<!-- Aux area: hint, update-rate button, Reset. -->
	<Grid Grid.Row="2">
		<Grid.ColumnDefinitions>
			<ColumnDefinition Width="3*"/>
			<ColumnDefinition Width="94*"/>
			<ColumnDefinition Width="3*"/>
		</Grid.ColumnDefinitions>
		<Grid.RowDefinitions>
			<RowDefinition Height="8*"/>
			<RowDefinition Height="84*"/>
			<RowDefinition Height="8*"/>
		</Grid.RowDefinitions>
		<Border Grid.Row="1" Grid.Column="1" Background="#FF1C1F2B" CornerRadius="14">
			<Grid>
				<Grid.ColumnDefinitions>
					<ColumnDefinition Width="4*"/>
					<ColumnDefinition Width="44*"/>
					<ColumnDefinition Width="2*"/>
					<ColumnDefinition Width="26*"/>
					<ColumnDefinition Width="2*"/>
					<ColumnDefinition Width="18*"/>
					<ColumnDefinition Width="4*"/>
				</Grid.ColumnDefinitions>
				<Grid.RowDefinitions>
					<RowDefinition Height="15*"/>
					<RowDefinition Height="70*"/>
					<RowDefinition Height="15*"/>
				</Grid.RowDefinitions>
				<TextBlock Grid.Row="1" Grid.Column="1" Text="{Binding HintText}" FontSize="{Binding FontMedium}"
						   Foreground="#FFCBD5E1" TextWrapping="Wrap" VerticalAlignment="Center" IsHitTestVisible="False"/>
				<Button Grid.Row="1" Grid.Column="3" Style="{StaticResource BarButton}" Background="#FF3D455C"
						Content="{Binding RateLabel}" FontSize="{Binding FontSmall}" Command="{Binding OnRate}"/>
				<Button Grid.Row="1" Grid.Column="5" Style="{StaticResource BarButton}" Background="#FF52576B"
						Content="Reset" FontSize="{Binding FontMedium}" Command="{Binding OnReset}"/>
			</Grid>
		</Border>
	</Grid>

	<!-- Bottom inset: diagnostics - root size, move events per second, last position, first args per event kind. -->
	<TextBlock Grid.Row="3" Margin="12,2,12,2" Text="{Binding DiagText}" FontSize="{Binding FontSmall}"
			   Foreground="#FF94A3B8" TextWrapping="Wrap" VerticalAlignment="Center" IsHitTestVisible="False"/>

	<!-- Board layer: placed by the script in root pixels. A picture only - the root takes all the input. -->
	<Canvas Grid.RowSpan="4" IsHitTestVisible="False">
		<Border Canvas.Left="{Binding BoardX}" Canvas.Top="{Binding BoardY}" Width="{Binding BoardSize}" Height="{Binding BoardSize}"
				Background="#FF0E1017" CornerRadius="10">
			<UniformGrid Rows="${GRID}" Columns="${GRID}">
${cells()}
			</UniformGrid>
		</Border>
${repeat(END_POINT_SLOTS, endPoint)}
${repeat(PIECE_SLOTS, (n) => piece(n, options.pieces))}

		<Border Canvas.Left="{Binding BoardX}" Canvas.Top="{Binding BoardY}" Width="{Binding BannerSize}" Height="{Binding BannerSize}"
				Background="#B30A0C12" CornerRadius="10">
			<TextBlock Text="{Binding BannerText}" FontSize="{Binding FontLarge}" FontWeight="Bold" Foreground="#FFF2CC40"
					   HorizontalAlignment="Center" VerticalAlignment="Center"/>
		</Border>
	</Canvas>
</Grid>
`;
}

/**
 * 세 장을 내보낸다. 화면이 아예 안 뜰 때 **원인을 가르기 위한** 것이다 - gizmo 의 Root XAML 만
 * 바꿔 끼우면서 어디까지 뜨는지 보면 된다 (스크립트는 셋 다 같은 것을 쓴다).
 *
 *   MoveLabMini    포인터 인자 없음 + Canvas.Left/Top   전부 이미 검증된 문법만 쓴다.
 *                  이것도 안 뜨면 XAML 내용이 아니라 에셋·gizmo·스크립트 설정 문제다
 *   MoveLabCanvas  포인터 인자 있음 + Canvas.Left/Top   Mini 는 뜨는데 이것이 안 뜨면 `PassEventArgsToCommand` 가 원인
 *   MoveLab        포인터 인자 있음 + TranslateTransform  Canvas 는 뜨는데 이것이 안 뜨면 transform 바인딩이 원인
 *
 * Canvas 판이 뜬다면 그대로 써도 된다 - 스크립트가 같으므로 기능 차이가 없다.
 */
const VARIANTS = [
	{ file: 'MoveLab.xaml', note: 'full', pointers: true, pieces: 'transform' },
	{ file: 'MoveLabCanvas.xaml', note: 'canvas positioning', pointers: true, pieces: 'canvas' },
	{ file: 'MoveLabMini.xaml', note: 'no pointer args', pointers: false, pieces: 'canvas' },
];

fs.mkdirSync(OUTPUT_DIR, { recursive: true });
for (const variant of VARIANTS) {
	fs.writeFileSync(path.join(OUTPUT_DIR, variant.file), render(variant), 'utf8');
	console.log(`wrote ${variant.file} (${variant.note})`);
}
console.log(`${PIECE_SLOTS} piece slots, ${END_POINT_SLOTS} end point slots`);
